server:
  port: 8000
  servlet:
      context-path: /

logging:
  config: classpath:logback-dev.xml

spring:
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
#    url: jdbc:mysql://localhost:3306/qnt_robot?useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: ninelock@505!
    url: jdbc:mysql://35.72.243.133:3306/qnt_robot?useSSL=false&serverTimezone=Asia/Shanghai
    username: admin
    password: D2BD5JHcfXyjWFYuEYvi
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 100
      maximum-pool-size: 500
      idle-timeout: 30000
      connection-timeout: 30000

sa-token:
  is-log: true
  timeout: -1
  is-print: false
  is-share: false
  log-level: info
  token-name: WST-DMS
  token-style: uuid
  is-concurrent: false
  active-timeout: 604800

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    banner: false
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    log-impl: com.ninelock.api.core.config.MybatisLogging
    cache-enabled: false

mybatis-plus-join:
  banner: false

qnt_robot:
  ip: 192.168.1.16
  port: 10000

detectDbInfo:
#  jdbcDriver: com.mysql.cj.jdbc.Driver
#  dbUrl: jdbc:mysql://localhost:3306/detect?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
#  dbName: detect
#  dbUser: root
#  dbPassword: ninelock@505!
  jdbcDriver: com.mysql.cj.jdbc.Driver
  dbUrl: jdbc:mysql://35.72.243.133:3306/detect?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
  dbName: detect
  dbUser: admin
  dbPassword: D2BD5JHcfXyjWFYuEYvi